// <auto-generated />
using System;
using AdminLTE.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AdminLTE.Migrations
{
    [DbContext(typeof(SampleContext))]
    [Migration("20200504172746_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AdminLTE.Models.Cities", b =>
                {
                    b.Property<int>("CitiesId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CityName");

                    b.HasKey("CitiesId");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("AdminLTE.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Adress");

                    b.Property<int?>("CitiesId");

                    b.Property<DateTime>("Created_Date");

                    b.Property<string>("CustomerName");

                    b.Property<string>("Notes");

                    b.HasKey("CustomerId");

                    b.HasIndex("CitiesId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("AdminLTE.Models.Customer", b =>
                {
                    b.HasOne("AdminLTE.Models.Cities", "Cities")
                        .WithMany()
                        .HasForeignKey("CitiesId");
                });
#pragma warning restore 612, 618
        }
    }
}
